swagger: '2.0'
info:
  title: 'Api Denizard'
  version: '1.0.0'
  description: 'Desafio Generation Brasil'
  termsOfService: 'http://swagger.io/terms/'
  contact:
    name: 'Suporte'
    email: 'denizard.oliveira@gmail.com'
  license:
    name: 'Licença MIT'
    url: 'https://opensource.org/licenses/MIT'