"""Criar tabela alunos

Revision ID: 7b822ba611ba
Revises: 
Create Date: 2024-09-13 12:39:38.188747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b822ba611ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alunos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=False),
    sa.Column('nota_primeiro_semestre', sa.Float(), nullable=False),
    sa.Column('nota_segundo_semestre', sa.Float(), nullable=False),
    sa.Column('nome_professor', sa.String(length=100), nullable=False),
    sa.Column('numero_sala', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alunos')
    # ### end Alembic commands ###
